packages:
  - packages/*
  - __configs__/*

catalog:
  '@babel/parser': ^7.28.0
  '@babel/types': ^7.28.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
  '@eslint/js': ^9.32.0
  '@pnpm/reviewing.dependencies-hierarchy': ^1001.0.16
  '@pnpm/workspace.find-packages': ^1000.0.27
  '@tsconfig/node-lts': ^22.0.2
  '@types/node': ^24.1.0
  '@vitejs/plugin-vue': 6.0.0
  '@vitejs/plugin-vue-jsx': ^5.0.1
  ansis: ^4.1.0
  es-module-lexer: ^1.7.0
  es-module-shims: ^2.6.1
  eslint: ^9.32.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-prettier: ^10.1.8
  eslint-flat-config-utils: ^2.1.1
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^52.0.2
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.3
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-pnpm: ^1.1.0
  eslint-plugin-prettier: ^5.5.3
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.4.0
  eslint-plugin-yaml: ^1.1.2
  eslint-plugin-yml: ^1.18.0
  eslint-typegen: ^2.3.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  globals: ^16.3.0
  http-server: ^14.1.1
  husky: ^9.1.7
  jsdom: ^26.1.0
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^16.1.4
  magic-string: ^0.30.17
  node-fetch: ^3.3.2
  prettier: ^3.6.2
  rimraf: ^6.0.1
  rollup: ^4.44.1
  tsdown: ^0.13.2
  tsx: ^4.20.3
  typescript: ^5.9.2
  typescript-eslint: ^8.38.0
  unocss: ^66.4.1
  unplugin-auto-import: 20.0.0
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^29.0.0
  v: ^0.0.0
  vi: ^0.0.0
  vit: ^0.0.0
  vite: 7.0.6
  vitest: ^3.2.4
  vue-eslint-parser: ^10.2.0
  yaml-eslint-parser: ^1.3.0
