export const GLOB_JS = '**/*.?([cm])js'
export const GLOB_JSX = '**/*.?([cm])jsx'
export const GLOB_TS = '**/*.?([cm])ts'
export const GLOB_TSX = '**/*.?([cm])tsx'
export const GLOB_JSON = '**/*.json'
export const GLOB_JSON5 = '**/*.json5'
export const GLOB_JSONC = '**/*.jsonc'
export const GLOB_YAML = '**/*.y?(a)ml'
export const GLOB_TOML = '**/*.toml'
export const GLOB_VUE = '**/*.vue'
const GLOB_SVELTE = '**/*.svelte'
export const GLOB_MARKDOWN = '**/*.md'
export const GLOB_HTML = '**/*.html'
const GLOB_CSS = '**/*.css'

export const GLOB_SRC = '**/*.?([cm])[jt]s?(x)'
